import { motion } from "framer-motion";
import { Brain, Target, MessageSquare, BarChart3, ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import DepartmentCard from "@/components/DepartmentCard";
import { departments, govtJobs } from "@/data/departments";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import robotInterview from "@/assets/robot-interview.png";

const features = [
  { icon: Brain, title: "AI-Powered Questions", desc: "Role-based questions generated by AI tailored to your domain" },
  { icon: MessageSquare, title: "Voice & Text Answers", desc: "Answer through text or voice — just like a real interview" },
  { icon: BarChart3, title: "Instant Feedback", desc: "Get detailed analysis on communication and technical skills" },
  { icon: Target, title: "Targeted Improvement", desc: "AI suggests areas where you need to improve" },
];

const Index = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero */}
      <section className="relative pt-32 pb-20 overflow-hidden" style={{ background: "var(--gradient-hero)" }}>
        <div className="absolute inset-0 opacity-20">
          <div className="absolute top-20 left-1/4 w-72 h-72 bg-primary/20 rounded-full blur-[100px]" />
          <div className="absolute bottom-10 right-1/4 w-96 h-96 bg-accent/20 rounded-full blur-[120px]" />
        </div>
        <div className="container mx-auto px-4 relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7 }}
              className="max-w-2xl"
            >
              <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/30 bg-primary/10 text-primary text-sm font-medium mb-6">
                <Brain className="h-4 w-4" /> AI-Powered Interview Prep
              </div>
              <h1 className="font-display text-4xl md:text-6xl font-bold text-foreground mb-5 leading-tight">
                Ace Your Next Interview with{" "}
                <span className="text-gradient">PrepAI</span>
              </h1>
              <p className="text-lg text-muted-foreground mb-8 max-w-xl">
                Practice mock interviews powered by AI. Get instant feedback on your answers, improve your confidence, and land your dream job.
              </p>
              <div className="flex flex-col sm:flex-row gap-3">
                <Link to="/register">
                  <Button size="lg" className="bg-gradient-primary text-primary-foreground font-semibold text-base px-8 hover:opacity-90">
                    Get Started Free <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
                <Link to="/departments">
                  <Button size="lg" variant="outline" className="border-border text-foreground hover:bg-secondary text-base px-8">
                    Explore Departments
                  </Button>
                </Link>
              </div>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.7, delay: 0.2 }}
              className="hidden lg:flex justify-center"
            >
              <img 
                src={robotInterview} 
                alt="Robot conducting an interview with a person" 
                className="w-full max-w-md h-auto rounded-xl shadow-glow object-cover"
              />
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="font-display text-2xl md:text-3xl font-bold text-center text-foreground mb-12">
            How <span className="text-gradient">PrepAI</span> Works
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="text-center p-6"
              >
                <div className="w-14 h-14 rounded-xl bg-gradient-primary mx-auto flex items-center justify-center mb-4">
                  <f.icon className="h-7 w-7 text-primary-foreground" />
                </div>
                <h3 className="font-display font-semibold text-foreground mb-2">{f.title}</h3>
                <p className="text-sm text-muted-foreground">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>


      {/* CTA */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="rounded-2xl bg-gradient-card border border-border p-10 md:p-16 text-center shadow-glow">
            <h2 className="font-display text-2xl md:text-3xl font-bold text-foreground mb-4">
              Ready to Ace Your Interview?
            </h2>
            <p className="text-muted-foreground mb-8 max-w-md mx-auto">
              Join thousands of students who improved their interview skills with AI-powered practice.
            </p>
            <Link to="/register">
              <Button size="lg" className="bg-gradient-primary text-primary-foreground font-semibold px-10 hover:opacity-90">
                Start Practicing Now
              </Button>
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Index;